import type { Metadata } from 'next';

import { geistMono, geistSans } from '@/fonts';

import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                suppressHydrationWarning
                className={`${geistSans.className} ${geistMono.className} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
